### ISSUE TITLE
Unexpected token 'export'

### ISSUE THREAD

**Issue by stanley355** [BurakGur/google-one-tap#1]
Hi, I'm building a Next.js dan want to have the google one tap feature on my app. However after following the tutorial, it seems I've always encountered this error:
![image](https://user-images.githubusercontent.com/53996155/147317312-ca3b9909-0a3b-4d0f-8452-ed9b451cb984.png)

Anybody having similar issue???

**Comment by miguelgoodfood** [comment]
I am experiencing the same issue :(

**Comment by BurakGur** [comment]
Thanks @stanley355 and @miguelgoodfood fixed by https://github.com/BurakGur/google-one-tap/commit/10bb2c38d45ca5af12214c2e991423a8cce11f52
