### ISSUE TITLE
Hey I'm facing origin not allowed issue in next js

### ISSUE THREAD

**Issue by arnab15** [BurakGur/google-one-tap#2]
![image](https://user-images.githubusercontent.com/45819720/172050275-2b0f074b-70d3-4a48-93d1-be3140c8063e.png)
I have used it in nextjs this way .
  const options = {
        client_id: "My client id", // required
        auto_select: false, // optional
        cancel_on_tap_outside: false, // optional
        context: "signin", // optional
    };

    useEffect(() => {
        googleOneTap(options, (response) => {
            // Send response to server
            console.log(response);
        });
    }, []);
    
    is there any other solution workaround for this issue?

**Comment by BurakGur** [comment]
This is not package issue. This is authorization problem. Please go to Google Console >  Credentials  > Your Web Application Project and add your project url (Ex: http://localhost:3000) to Authorized JavaScript origins. 

I also added nextjs example and demo to project folder.
